[ParallelTNNLayers/test]─(master↑2|✔)─ python benchmark_conv2d_cp.py benchmark_conv2d_rcp.py benchmark_dense_cp.py
/usr/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Using numpy backend.
2019-05-13 08:33:27.451640: E tensorflow/core/platform/default/device_tracer.cc:142] Failed to initialize CUPTI: 35
entry {
  name: "TensorFlowBenchmark.TF_normal_op"
  iters: 1024
  wall_time: 0.0004800558090209961
  extras {
    key: "allocator_maximum_num_bytes_GPU_0_bfc"
    value {
      double_value: 140288.0
    }
  }
}

entry {
  name: "TensorFlowBenchmark.TF_normal_nhwc_op"
  iters: 1024
  wall_time: 0.000408172607421875
  extras {
    key: "allocator_maximum_num_bytes_GPU_0_bfc"
    value {
      double_value: 140288.0
    }
  }
}

entry {
  name: "TensorFlowBenchmark.TF_original_cp_op"
  iters: 1024
  wall_time: 0.0005362033843994141
  extras {
    key: "allocator_maximum_num_bytes_GPU_0_bfc"
    value {
      double_value: 91096.0
    }
  }
}

entry {
  name: "TensorFlowBenchmark.custom_fused_op"
  iters: 1024
  wall_time: 0.0004919767379760742
  extras {
    key: "allocator_maximum_num_bytes_GPU_0_bfc"
    value {
      double_value: 132056.0
    }
  }
}

entry {
  name: "TensorFlowBenchmark.sequencer_op"
  iters: 1024
  wall_time: 0.0004942417144775391
  extras {
    key: "allocator_maximum_num_bytes_GPU_0_bfc"
    value {
      double_value: 93568.0
    }
  }
}

entry {
  name: "TensorFlowBenchmark.sequencer_nhwc_op"
  iters: 1024
  wall_time: 0.0003008842468261719
  extras {
    key: "allocator_maximum_num_bytes_GPU_0_bfc"
    value {
      double_value: 65536.0
    }
  }
}

[ParallelTNNLayers/test]─(master↑2|✔)─ python benchmark_conv2d_rcp.py
/usr/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Using numpy backend.
WARNING:tensorflow:Falling back to exponential-space implementation of einsum() because index "r" is summed over more than two inputs.
2019-05-13 08:33:58.822574: E tensorflow/core/platform/default/device_tracer.cc:142] Failed to initialize CUPTI: 35
entry {
  name: "TensorFlowBenchmark.TF_normal_op"
  iters: 1024
  wall_time: 0.0004967451095581055
  extras {
    key: "allocator_maximum_num_bytes_GPU_0_bfc"
    value {
      double_value: 140288.0
    }
  }
  extras {
    key: "allocator_maximum_num_bytes_cuda_host_bfc"
    value {
      double_value: 52.0
    }
  }
}

entry {
  name: "TensorFlowBenchmark.TF_einsum_op"
  iters: 1024
  wall_time: 0.0007981061935424805
  extras {
    key: "allocator_maximum_num_bytes_GPU_0_bfc"
    value {
      double_value: 176128.0
    }
  }
  extras {
    key: "allocator_maximum_num_bytes_cuda_host_bfc"
    value {
      double_value: 176.0
    }
  }
}

entry {
  name: "TensorFlowBenchmark.fused_op"
  iters: 1024
  wall_time: 0.0009551048278808594
  extras {
    key: "allocator_maximum_num_bytes_GPU_0_bfc"
    value {
      double_value: 132876.0
    }
  }
  extras {
    key: "allocator_maximum_num_bytes_cuda_host_bfc"
    value {
      double_value: 44.0
    }
  }
}

entry {
  name: "TensorFlowBenchmark.TF_orig_op"
  iters: 1024
  wall_time: 0.0009757280349731445
  extras {
    key: "allocator_maximum_num_bytes_GPU_0_bfc"
    value {
      double_value: 1442892.0
    }
  }
  extras {
    key: "allocator_maximum_num_bytes_cuda_host_bfc"
    value {
      double_value: 280.0
    }
  }
}

[ParallelTNNLayers/test]─(master↑2|✔)─ python benchmark_dense_cp.py
/usr/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Using numpy backend.
WARNING:tensorflow:Falling back to exponential-space implementation of einsum() because index "r" is summed over more than two inputs.
WARNING:tensorflow:Falling back to exponential-space implementation of einsum() because index "r" is summed over more than two inputs.
2019-05-13 08:34:20.952336: E tensorflow/core/platform/default/device_tracer.cc:142] Failed to initialize CUPTI: 35
entry {
  name: "TensorFlowBenchmark.TF_GEMM_op"
  iters: 1024
  wall_time: 0.00047969818115234375
  extras {
    key: "allocator_maximum_num_bytes_GPU_0_bfc"
    value {
      double_value: 1081344.0
    }
  }
  extras {
    key: "allocator_maximum_num_bytes_cuda_host_bfc"
    value {
      double_value: 48.0
    }
  }
}

entry {
  name: "TensorFlowBenchmark.TF_rebuild_op"
  iters: 1024
  wall_time: 0.002299785614013672
  extras {
    key: "allocator_maximum_num_bytes_GPU_0_bfc"
    value {
      double_value: 145950976.0
    }
  }
  extras {
    key: "allocator_maximum_num_bytes_cuda_host_bfc"
    value {
      double_value: 168.0
    }
  }
}

entry {
  name: "TensorFlowBenchmark.TF_einsum_op"
  iters: 1024
  wall_time: 0.001816868782043457
  extras {
    key: "allocator_maximum_num_bytes_GPU_0_bfc"
    value {
      double_value: 154877952.0
    }
  }
  extras {
    key: "allocator_maximum_num_bytes_cuda_host_bfc"
    value {
      double_value: 200.0
    }
  }
}

entry {
  name: "TensorFlowBenchmark.custom_fused_op"
  iters: 1024
  wall_time: 0.0035219192504882812
  extras {
    key: "allocator_maximum_num_bytes_GPU_0_bfc"
    value {
      double_value: 121856.0
    }
  }
  extras {
    key: "allocator_maximum_num_bytes_cuda_host_bfc"
    value {
      double_value: 28.0
    }
  }
}
